from __future__ import annotations
"""othello_match_runner.py
A small framework to run head‑to‑head Othello/Reversi matches between text‑mode
engines that speak (a subset of) the Go Text Protocol (GTP).

Revision history
----------------
• **2025‑06‑14**   Add `win_to_wsl_path()` helper.
• **2025‑06‑14**   *Fix*: every move generated by one engine is now **mirrored**
  into the opponent via a `play <color> <move>` command so that both engines
  keep an identical board state.

Requirements
------------
• Python ≥ 3.9
• Executable paths supplied via *config.py*::

    leelaz      = "C:/engines/leelaz.exe"
    edax        = "C:/engines/edax.exe"
    kalmia      = "C:/engines/kalmia.exe"
    egaroucid   = "C:/engines/egaroucid.exe"
    rundir       = "C:/tmp/engine_workdir"
    results_root = "C:/tmp/othello_results"
    leelaz_args  = ["-g", "-q"]
    match_args   = ["-g", "-q"]

Edit those paths and the default Leela arguments to suit your setup.
"""

from dataclasses import dataclass, field
from pathlib import Path, PureWindowsPath
from multiprocessing import Pool, cpu_count
from uuid import uuid4
import subprocess
import tarfile
import csv
import hashlib
import gzip
import os
from typing import List, Tuple, Dict

# ---------------------------------------------------------------------------
# Configuration helpers (imported from user's config.py)
# ---------------------------------------------------------------------------

try:
    from config import (
        leelaz,
        match_args,
        edax,
        kalmia,
        egaroucid,
        rundir,
        results_root,
        save_gen_dir_,
        network,
        adri_gen_dir_
    )
except ImportError as exc:
    raise RuntimeError("config.py with engine paths is required") from exc

LEELA_DEFAULT_VISITS = 10000  # default visits for Leela
SGF_HEADER = "(;GM[2]FF[4]SZ[8]"
SGF_FOOTER = ")\n"

Path(results_root).mkdir(parents=True, exist_ok=True)

# ---------------------------------------------------------------------------
# Miscellaneous helpers
# ---------------------------------------------------------------------------

def win_to_wsl_path(win_path: str | os.PathLike) -> str:
    """Convert an absolute Windows file‑system path to its WSL counterpart."""
    p = PureWindowsPath(str(win_path))
    if not p.drive:
        raise ValueError(f"Cannot convert relative path '{win_path}'.")
    drive = p.drive.rstrip(":").lower()
    rest = "/".join(p.parts[1:])
    return f"/mnt/{drive}/{rest}"


def send_cmd(proc: subprocess.Popen, cmd: str) -> Tuple[str, List[str]]:
    """Send *one* GTP command and wait for the reply (header + payload)."""
    proc.stdin.write(cmd + "\n")
    proc.stdin.flush()
    # print(cmd + "\n", flush=True)
    header = proc.stdout.readline()
    payload: List[str] = []
    while True:
        line = proc.stdout.readline()
        if line in ("\n", ""):
            break
        payload.append(line.rstrip("\n"))
    return header.lstrip("= ?").strip(), payload


def sha256_short(path: str | Path, n: int = 8) -> str:
    path = Path(path)
    sha_path = path.with_suffix('.sha256')
    if not sha_path.exists():
        print(f"{sha_path} not found. Will compute hash on the fly.")
        h = hashlib.sha256()
        with gzip.open(path, "rb") as f:
            for chunk in iter(lambda: f.read(8192), b""):
                h.update(chunk)
        sha256sum = h.hexdigest()
        sha_path.write_text(sha256sum+" "+path.name)
    else:
        sha256sum = sha_path.read_text().strip().split()[0]

    return sha256sum[:n]


# ---------------------------------------------------------------------------
# Engine wrapper
# ---------------------------------------------------------------------------

@dataclass
class Engine:
    name: str
    exe: str | Path
    category: str
    extra: List[str] = field(default_factory=list)
    proc: subprocess.Popen | None = field(init=False, default=None)
    cwd: str | Path | None = None

    def reset(self):
        send_cmd(self.proc, "boardsize 8")
        send_cmd(self.proc, "clear_board")
        if self.category.startswith("leelaz") or self.category.startswith("lz"):
            send_cmd(self.proc, "clear_cache")

    def start(self):
        if self.proc is not None:
            return
        self.proc = subprocess.Popen(
            [self.exe, *self.extra],
            cwd=self.cwd,
            text=True,
            bufsize=1,
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            # stderr=subprocess.STDOUT,
        )
        self.reset()
        
    def restart(self, soft=False):
        if self.proc is None:
            self.start()
        elif soft:
            self.reset()
        else:
            self.close()
            self.start()

    def close(self):
        if self.proc is None:
            return
        try:
            send_cmd(self.proc, "quit")
        except Exception:
            pass
        self.proc.kill()
        self.proc = None

    # ---- gameplay helpers -------------------------------------------------
    def genmove(self, colour: str) -> str:
        header, _ = send_cmd(self.proc, f"genmove {colour}")
        return header.strip()

    def play_move(self, colour: str, move: str):
        # send_cmd(self.proc, "showboard")
        # h, p = send_cmd(self.proc, f"play {colour} {move}")
        # print(f"play {colour} {move} ---> <{h}> ({p})")
        send_cmd(self.proc, f"play {colour} {move}")

    def final_score(self) -> str:
        header, _ = send_cmd(self.proc, "final_score")
        return header

    def short(self) -> str:
        return self.name.replace(" ", "_")


class LeelaEngine(Engine):
    def __init__(self,
                 net_path: str | Path,
                 visits: int = LEELA_DEFAULT_VISITS,
                 exe: str | Path = None,
                 **kwargs):
        wsl_path = win_to_wsl_path(net_path)
        wsl_path = Path(wsl_path)
        net_hash = sha256_short(wsl_path)
        if exe is None:
            exe = leelaz
            name = "Leela-Zero"
            category = "leelaz"
        else:
            code = Path(exe).parts[-2] # adri, flip, ...
            name = "LZ-" + code + "-" + net_hash
            category = "lz" + code + "-" + net_hash
        super().__init__(
            name=name,
            exe=exe,
            category=category,
            extra=match_args + ["-w", str(net_path), "-v", str(visits)] + ["--std-othello"],
            **kwargs
        )


class EdaxEngine(Engine):
    def __init__(self,
                 level: int | None = None):
        code = "max" if level is None else str(level)
        category = "edax-" + code
        name = "Edax-" + code
        extra = ["--gtp", "-vv"]
        if level is not None:
            extra += ["-l", str(level)]
        super().__init__(name=name,
                         exe=edax,
                         category=category,
                         extra=extra,
                         cwd="/mnt/d/lzo/bin/edax/"
                         )


class KalmiaEngine(Engine):
    def __init__(self, strength: str):
        assert strength in ["custom", "easy", "normal", "proffesional", "superhuman"]
        category = f"kalmia-{strength}"
        super().__init__("kalmia",
            exe="/mnt/d/lzo/bin/kalmia/Kalmia",
            category=category,
            extra=["--mode", "gtp", "--difficulty", strength],
            cwd="/mnt/d/lzo/bin/kalmia/"
        )


class EgaroucidEngine(Engine):
    def __init__(self):
        super().__init__("egaroucid", egaroucid, "egaroucid")


# ---------------------------------------------------------------------------
# SGF helpers
# ---------------------------------------------------------------------------

_ALPHA = "abcdefgh"

def coord_to_sgf(m: str) -> str:
    if m.lower() == "pass":
        return ""
    x = _ALPHA.index(m[0].lower())
    y = int(m[1]) - 1
    return f"{_ALPHA[x]}{_ALPHA[y]}"


# ---------------------------------------------------------------------------
# Game driver
# ---------------------------------------------------------------------------

@dataclass
class GameResult:
    moves: int
    res_a: str
    res_b: str
    sgf: Path


class Game:
    def __init__(self,
                 black: Engine,
                 white: Engine,
                 no: int,
                 match_id: str,
                 out_dir: Path,
                 soft_restart: bool = False):
        self.B = black
        self.W = white
        self.no = no
        self.mid = match_id
        self.out = out_dir
        self.soft_restart = soft_restart

    def _sgf(self, seq, res_tag):
        parts = [SGF_HEADER, f"PB[{self.B.name}]", f"PW[{self.W.name}]", f"RE[{res_tag}]"]
        for col, mv in seq:
            if mv.lower() == "resign":
                continue
            parts.append(f";{col}[{coord_to_sgf(mv)}]")
        parts.append(SGF_FOOTER)
        return "".join(parts)

    def play(self) -> GameResult:
        # fresh engines
        self.B.restart(self.soft_restart)
        self.W.restart(self.soft_restart)

        history = []  # ("B"|"W", move)
        to_move = "black"
        passes = 0
        moves = 0
        discs = 4
        resigned = False

        while True:
            eng = self.B if to_move == "black" else self.W
            opp = self.W if to_move == "black" else self.B

            mv = eng.genmove(to_move).lower()
            if mv.startswith("wrong"):
                break
            moves += 1
            # print(f"[{to_move} {mv}]")
            history.append(("B" if to_move == "black" else "W", mv))
            # print(history)

            # mirror the move to the opponent so its board state matches
            if mv == "pass":
                opp.play_move(to_move, "pass")
            elif mv != "resign":
                opp.play_move(to_move, mv)
                discs += 1
                if discs == 64:
                    break

            if mv == "resign":
                resigned = True
                break
            if mv == "pass":
                passes += 1
                if passes == 2:
                    break
            else:
                passes = 0

            to_move = "white" if to_move == "black" else "black"

        if resigned:
            res_a = res_b = "W+R" if to_move == "black" else "B+R"
        else:
            res_a = self.B.final_score()
            res_b = self.W.final_score()

        if res_a.startswith("unknown"):
            res_a = res_b
        sgf_txt = self._sgf(history, res_a)
        fn = f"{self.mid}_g{self.no:03d}_{self.B.short()}-B_{self.W.short()}-W.sgf"
        fp = self.out / fn
        with open(fp, "w", encoding="utf-8") as f:
            f.write(sgf_txt)

        self.B.close()
        self.W.close()
        return GameResult(moves, res_a, res_b, fp)


# ---------------------------------------------------------------------------
# Match driver
# ---------------------------------------------------------------------------

@dataclass
class MatchRunner:
    A: Engine
    B: Engine
    games: int = 100
    root: Path = Path(results_root)
    soft: bool = False

    def run(self) -> Tuple[str, List[Dict]]:
        assert self.games % 2 == 0, "games must be even"
        mid = uuid4().hex[:8]
        tmp = self.root / "tmp" / mid
        tmp.mkdir(parents=True, exist_ok=True)

        print(f"Starting match {mid}")
        rows: List[Dict] = []
        for g in range(self.games):
            blk, wht = (self.A, self.B) if g % 2 == 0 else (self.B, self.A)
            result = Game(blk, wht, g + 1, mid, tmp, self.soft).play()
            winner = blk.name if result.res_a.startswith('B') else wht.name
            print(f"Game {g+1} won by {winner} with score {result.res_a}")
            rows.append({
                "match_id": mid,
                "game_no": g + 1,
                "black": blk.name,
                "white": wht.name,
                f"{self.A.name}_result": result.res_a,
                f"{self.B.name}_result": result.res_b,
                "move_count": result.moves,
                "sgf_file": result.sgf.name,
            })

        # tar.gz of SGFs copied under both categories
        tar_name = f"match_{mid}.tar.gz"
        tar_tmp = tmp.parent / tar_name
        with tarfile.open(tar_tmp, "w:gz") as tar:
            for f in tmp.glob("*.sgf"):
                tar.add(f, arcname=f.name)

        for cat in (self.A.category, self.B.category):
            dest = self.root / cat
            dest.mkdir(parents=True, exist_ok=True)
            (dest / tar_name).write_bytes(tar_tmp.read_bytes())

        # clean tmp
        for f in tmp.glob("*"):
            f.unlink()
        tmp.rmdir()

        return mid, rows


# ---------------------------------------------------------------------------
# Batch helper
# ---------------------------------------------------------------------------

def _work(spec):
    A, B, n, r, soft = spec
    mid, rows = MatchRunner(A, B, n, Path(r), soft).run()
    return rows


def run_batch(pairs: List[Tuple[Engine, Engine]], games: int = 100, workers: int = 1, csv_out: str | Path | None = None, soft: bool = False):
    if csv_out is None:
        csv_out = Path(results_root) / "results.csv"

    specs = [(a, b, games, str(results_root), soft) for a, b in pairs]
    all_rows: List[Dict] = []

    if workers == 1:
        for s in specs:
            all_rows.extend(_work(s))
    else:
        with Pool(min(cpu_count(), workers)) as pool:
            for rows in pool.imap_unordered(_work, specs):
                all_rows.extend(rows)

    # write CSV
    fields = [
        "match_id", "game_no", "black", "white",
        *sorted({k for r in all_rows for k in r if k.endswith("_result")}),
        "move_count", "sgf_file",
    ]
    with open(csv_out, "a", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        if os.path.getsize(csv_out) == 0:
            writer.writeheader()
        writer.writerows(all_rows)

    print(f"Batch finished – csv saved to {csv_out}")


# ---------------------------------------------------------------------------
# Demo
# ---------------------------------------------------------------------------


def elys_net(gen: int | None = None):
    if gen is None:
        return network
    else:
        return save_gen_dir_ + f"\\{gen}\\leelaz-model-{gen*4000}.txt.gz"

def adri_net(gen: int = 300):
    return adri_gen_dir_ + f"\\{gen}\\{gen}gen.txt.gz"


if __name__ == "__main__":
    from config import *

    # adri50  = LeelaEngine(adri_net(50))
    kalmia_easy = KalmiaEngine("easy")
    kalmia_normal = KalmiaEngine("normal")
    kalmia_pro = KalmiaEngine("proffesional")
    kalmia_super = KalmiaEngine("superhuman")
    default = LeelaEngine(elys_net())
    default109 = LeelaEngine(elys_net(109))
    adrieng = LeelaEngine(elys_net(), exe=lzadri)
    std_othello = LeelaEngine(elys_net(), exe=lzflip)
    # std_othello109 = LeelaEngine(elys_net(109), exe=lzflip)
    edax_default = EdaxEngine()
    edax_lvl20 = EdaxEngine(20)

    # edax_engine = EdaxEngine()

    run_batch([
        (EdaxEngine(10), LeelaEngine(elys_net()))
    ], games=20, workers=1, soft=True)
